### ISSUE TITLE
readme or manuel

### ISSUE THREAD

**Issue by TobjasR** [miguelob/ICS-Hacking#6]
a readme or manual would me super awesome to get started.
I did ./main.py, nothing but errors happen and I don't know that I have missed… 
```
$ ./main.py 
from: can't read /var/mail/numpy
from: can't read /var/mail/S7comm
from: can't read /var/mail/PnetPbus
from: can't read /var/mail/PnetPbus
import-im6.q16: unable to grab mouse `': No such file or directory @ error/xwindow.c/XSelectWindow/9187.
from: can't read /var/mail/tkinter
from: can't read /var/mail/pymodbus.client.sync
from: can't read /var/mail/SCADA
from: can't read /var/mail/time
import-im6.q16: unable to grab mouse `': No such file or directory @ error/xwindow.c/XSelectWindow/9187.
./main.py: line 12: syntax error near unexpected token `('
./main.py: line 12: `def clearScreen():'
```

**Comment by miguelob** [comment]
Hi @TobjasR!

I see that you are trying to run the package. In order to do that, you have first to download that [folder](https://github.com/miguelob/ICS-Hacking/tree/main/packet). One you have the folder in your computer, first run pip3 install -r requirements.txt so you have all the modules required. Then you just have to execute the main by python3 ./main.py (important to do it on the folder level where the main.py is and the requirements.txt).

If you need more information on how each module works, you just have to see the Read.me of the repository. 

Let me know if you need more information.

**Comment by TobjasR** [comment]
hi @miguelob thank you for your quick reply! :) I had it downloaded and requirements installed but forgot the -r option… and btw the main.py is missing the python shebang (#! /usr/bin/python3) 
however I'm still getting an error:
```
$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from PnetPbus import Discovery
  File "/home/[SNIP]/ICS-Hacking_1.0/PnetPbus/Discovery.py", line 9, in <module>
    class Discovery(mac):
NameError: name 'mac' is not defined
```

**Comment by miguelob** [comment]
@TobjasR for this project no python shebang is needed. Can you confirm me that you are on commit ab60080ab1652e126b0038132201e11c6b81f141? I change the main.py to solve other issues. To me looks like one of the following issues:
- You have an older version if the code.
- you are executing the code without the rest of the folders needed.

Text me back with the commit you are in and if it is the last one I will work on a solution.
Thanks.

**Comment by TobjasR** [comment]
hi @miguelob , I mean with the shebang `./main.py` would work without the `python3`. 
I had tried it with the 1.0 release… Now, I've downloaded ab60080 (ICS-Hacking-ab60080ab1652e126b0038132201e11c6b81f141.zip) but there's no main.py file in it…

**Comment by miguelob** [comment]
Okay that was the problem, I'm working on fixes for the 1.0 release. If you see the other issues, people have found different issues that on the release ab60080ab1652e126b0038132201e11c6b81f141 I have fixed, but I haven't created a new release until I see everything is working fine. 
To find the main.py, go into the repo folder and cd ./package and there you will find the main.py with the new requirements.txt (reinstall needed because I have also fixed it) and both folders with connect. Try to execute that main.py and let me know if everything is working now.

Thanks for telling me about the shebang.

**Comment by TobjasR** [comment]
hi @miguelob , thanks for the quick help, now it's working and I get into the menu.
Maybe I haven't understood the project correctly… I thought it's (also) meant to emulate ICS, e.g. a SCADA and S7 things, kind of like Snap7 or Bevywise do.
Trying to start the SCADA Lab I think I encountered a type error:
```
==========================

       ICS-Hacking

==========================
® by Miguel Oleo Blanco


1 -- S7Comm
2 -- S7Comm-plus
3 -- SCADA
4 -- Profinet & Profibus
5 -- Exit
Enter your choice: 3
Please, type in the destination IP: 192.168.1.10
Please, type in the RACK (DEFAULT IS 0): 0
Please, type in the the SLOT (DEFAULT IS 1): 1
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    plc.connect(IP,RACK,SLOT)   #Connects to the client
  File "/home/tobjasr/.local/lib/python3.8/site-packages/snap7/client.py", line 25, in f
    code = func(*args, **kw)
  File "/home/tobjasr/.local/lib/python3.8/site-packages/snap7/client.py", line 197, in connect
    c_int(rack), c_int(slot))
TypeError: an integer is required (got type str)
```

**Comment by miguelob** [comment]
Okay thx for letting me know. The project is in an early state but ill work on a fix this week. I have moved that issue to another issue page.

Thx for letting me know and sorry that is not working. I'll get back to you with a fix. Whenever is everything fixed, ill release a new version with the previous fixes and this one.

Thanks.
